### PR TITLE
Changed baseimage to allow for multiarch build (specifically arm64)

### PR DESCRIPTION
**Pull request by jeanluc162**

### CODE REVIEW

**Comment by jackbritchford** [comment]
I created a similar PR to update the version of the base image but it's from Dockerhub
Could you pin the version of alpine you're using to prevent issues builds pulling 'latest'?

**Comment by jeanluc162** [comment]
> Could you pin the version of alpine you're using to prevent issues builds pulling 'latest'?
I've pinned the version to 3.17.1 (current latest)

**Comment by zzzi2p** [comment]
@eyedeekay

**Comment by eyedeekay** [comment]
LGTM, I'll test locally then merge.

**Comment by eyedeekay** [comment]
closes #34

**Comment by eyedeekay** [comment]
Thanks @jeanluc162

**Pull request merged**
